{
 "title": "Submariner Single Gateway Aggregate Netperf Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "All Node Aggregate Bandwidth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "sumSeries(bandwidth.single_gw.netperf.*)"
    }
   ]
  },
  {
   "title": "Current Aggregated Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(bandwidth.single_gw.netperf.*)"
    }
   ]
  },
  {
   "title": "cluster1-noha-worker1-node Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "bandwidth.single_gw.netperf.cluster1-noha-worker1-node"
    }
   ]
  },
  {
   "title": "cluster1-noha-worker2-node Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "target": "bandwidth.single_gw.netperf.cluster1-noha-worker2-node"
    }
   ]
  },
  {
   "title": "cluster1-noha-worker3-node Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "target": "bandwidth.single_gw.netperf.cluster1-noha-worker3-node"
    }
   ]
  }
 ]
}