{
 "title": "Submariner Single-Active Gateway Iperf Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "All Node Aggregate Single-Active GW Iperf Download Bandwidth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "sumSeries(submariner.single_gw.vxlan.iperf.download.*.*)"
    }
   ]
  },
  {
   "title": "All Node Aggregate Single-Active GW Iperf Upload Bandwidth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "sumSeries(submariner.single_gw.vxlan.iperf.upload.*.*)"
    }
   ]
  },
  {
   "title": "Current Aggregated Download Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(submariner.single_gw.vxlan.iperf.download.*.*)"
    }
   ]
  },
  {
   "title": "Current Aggregated Download Upload Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(submariner.single_gw.vxlan.iperf.upload.*.*)"
    }
   ]
  },
  {
   "title": "Cluster-1 Iperf Group-1",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "submariner.single_gw.vxlan.iperf.*.group1.*"
    }
   ]
  },
  {
   "title": "Cluster-1 Iperf Group-2",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "submariner.single_gw.vxlan.iperf.*.group2.*"
    }
   ]
  }
 ]
}