{
 "title": "Submariner Multi-Active Gateway Aggregate Netperf Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "All Node Aggregate Active-Active Bandwidth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "sumSeries(submariner.multi_gw.vxlan.netperf.*.*)"
    }
   ]
  },
  {
   "title": "Current Aggregated Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(submariner.multi_gw.vxlan.netperf.*.*)"
    }
   ]
  },
  {
   "title": "Cluster-1 Netperf Group-1",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "submariner.multi_gw.vxlan.netperf.group1.*"
    }
   ]
  },
  {
   "title": "Cluster-1 Netperf Group-2",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "submariner.multi_gw.vxlan.netperf.group2.*"
    }
   ]
  }
 ]
}